### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Redick01** [dromara/stream-query#23]
jdk：1.8
stream-query：1.4.4

异常：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dynamicMapperHandler' defined in class path resource [io/redick/stream/config/DynamicMapperHandlerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.dromara.streamquery.stream.plugin.mybatisplus.engine.mapper.DynamicMapperHandler]: Factory method 'dynamicMapperHandler' threw exception; nested exception is java.lang.IllegalStateException: java.lang.ClassNotFoundException: io.redick.stream.po..Users.penghuiliu.geek_learn.stream-query-demo.target.classes.io.redick.stream.po.Name

**Comment by VampireAchao** [comment]
麻烦能提供一下对应的`demo`供复现

**Comment by yu8440348** [comment]
我也一样的，扫描不到类

**Comment by VampireAchao** [comment]
> 我也一样的，扫描不到类

提供一下对应的demo供复现
